### PR TITLE
CE-4981 Exact Formula Search returns incorrect results #280

### LINKED ISSUE #280: CE-4981 Exact Formula Search returns incorrect results
This is a part of the CCDAdvancedSearch resource. Needs to exclude is_markush values.

### PR DESCRIPTION
**Pull request by bridirks**

### CODE REVIEW

File: src/main/java/gov/epa/ccte/api/chemical/repository/ChemicalSearchRepository.java [hunk 1]
```diff
@@ -37,32 +37,31 @@ public interface ChemicalSearchRepository extends JpaRepository<ChemicalSearch,
     List<CcdChemicalSearchResult> containCcd(@Param("searchWord") String searchWord);
     // Advance search parameters
     
-    @Query(value = "select distinct ms_ready_dtxsid from ch.v_msready_search where mol_formula = :formula and substance_public is true ", nativeQuery = true)
+    @Query(value = "select distinct ms_ready_dtxsid from ch.v_msready_search where mol_formula = :formula", nativeQuery = true)
```
Comment (janetleeFederal) [inline src/main/java/gov/epa/ccte/api/chemical/repository/ChemicalSearchRepository.java:40]: Noting that she is removing the substance_public is true bc all the chemicals are public already.

**Review by janetleeFederal — APPROVED** [review]
Per chat with Brad and Brianna, I am ok with this PR. I made a notation on the item Brad pointed out re: substance_public condition being removed. Per Brianna the chemicals on the table are public ones already.
